name: Update README with streak stats

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace streak stats URL with token
        run: |
          sed -i "s|STREAK_STATS_URL|https://streak-stats.demolab.com?user=khasanjon-dev&theme=radical&token=${{ secrets.STREAK_STATS_TOKEN }}|g" README.md
          cat README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update streak stats URL"
          git push
